# Generated by Django 4.2.6 on 2023-10-23 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='imagenes/')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('status_sale', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='imagenes/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csl_app.typecategory')),
                ('product_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csl_app.productstatus')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sale', models.DateField()),
                ('product_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csl_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryProductBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_buy', models.DateField()),
                ('product_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csl_app.product')),
            ],
        ),
    ]
